name = "PathIntersections"
uuid = "4c1a95c7-462a-4a7e-b284-959c63fbf1dc"
authors = ["Christina G Taylor"]
version = "0.1.0"

[deps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
julia = "1.7.2"
StructArrays = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
